### ISSUE TITLE
그래프 생성 시 오류

### ISSUE THREAD

**Issue by zeromeJ** [jny384/SWP1#1]
[현상]
그래프를 생성할 수 없다며 기능 동작 실패
[재현 방법]
1. ssh 접속 시 -Y 옵션을 사용하지 않고 접속
2. 서버 실행
3. http://XXX.YYY.ZZZ.WWW/fig 접속
4. 값 입력 후 submit
[개선 방향]
ssh -Y 옵션으로 접속하지 않고 서버를 실행하더라도 그래프 생성에 문제가 발생하지 않도록

**Comment by jny384** [comment]
[로그 확인 결과 문제가 발생하는 코드]
https://github.com/jny384/SWP1/blob/c8bec9162db44dcc0bac3293e3ca757b505176c7/graph.py#L26

**Comment by zeromeJ** [comment]
[로그 확인 결과 문제가 발생하는 코드]
https://github.com/jny384/SWP1/blob/c8bec9162db44dcc0bac3293e3ca757b505176c7/graph.py#L26
